"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
const flatbuffers = require("./flatbuffers");
/**
 * @constructor
 */
var Mod;
(function (Mod) {
    var proto;
    (function (proto) {
        class Chat {
            constructor() {
                this.bb = null;
                this.bb_pos = 0;
            }
            /**
             * @param number i
             * @param flatbuffers.ByteBuffer bb
             * @returns Chat
             */
            __init(i, bb) {
                this.bb_pos = i;
                this.bb = bb;
                return this;
            }
            ;
            /**
             * @param flatbuffers.ByteBuffer bb
             * @param Chat= obj
             * @returns Chat
             */
            static getRootAsChat(bb, obj) {
                return (obj || new Chat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
            }
            ;
            /**
             * @param flatbuffers.ByteBuffer bb
             * @param Chat= obj
             * @returns Chat
             */
            static getSizePrefixedRootAsChat(bb, obj) {
                bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                return (obj || new Chat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
            }
            ;
            displayName(optionalEncoding) {
                var offset = this.bb.__offset(this.bb_pos, 4);
                return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
            }
            ;
            content(optionalEncoding) {
                var offset = this.bb.__offset(this.bb_pos, 6);
                return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
            }
            ;
            /**
             * @param flatbuffers.Builder builder
             */
            static startChat(builder) {
                builder.startObject(2);
            }
            ;
            /**
             * @param flatbuffers.Builder builder
             * @param flatbuffers.Offset displayNameOffset
             */
            static addDisplayName(builder, displayNameOffset) {
                builder.addFieldOffset(0, displayNameOffset, 0);
            }
            ;
            /**
             * @param flatbuffers.Builder builder
             * @param flatbuffers.Offset contentOffset
             */
            static addContent(builder, contentOffset) {
                builder.addFieldOffset(1, contentOffset, 0);
            }
            ;
            /**
             * @param flatbuffers.Builder builder
             * @returns flatbuffers.Offset
             */
            static endChat(builder) {
                var offset = builder.endObject();
                return offset;
            }
            ;
            /**
             * @param flatbuffers.Builder builder
             * @param flatbuffers.Offset offset
             */
            static finishChatBuffer(builder, offset) {
                builder.finish(offset);
            }
            ;
            /**
             * @param flatbuffers.Builder builder
             * @param flatbuffers.Offset offset
             */
            static finishSizePrefixedChatBuffer(builder, offset) {
                builder.finish(offset, undefined, true);
            }
            ;
            static createChat(builder, displayNameOffset, contentOffset) {
                Chat.startChat(builder);
                Chat.addDisplayName(builder, displayNameOffset);
                Chat.addContent(builder, contentOffset);
                return Chat.endChat(builder);
            }
        }
        proto.Chat = Chat;
    })(proto = Mod.proto || (Mod.proto = {}));
})(Mod = exports.Mod || (exports.Mod = {}));
