"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * @constructor
 */
var Mod;
(function (Mod) {
    var proto;
    (function (proto) {
        class UUID {
            constructor() {
                this.bb = null;
                this.bb_pos = 0;
            }
            /**
             * @param number i
             * @param flatbuffers.ByteBuffer bb
             * @returns UUID
             */
            __init(i, bb) {
                this.bb_pos = i;
                this.bb = bb;
                return this;
            }
            ;
            /**
             * @returns flatbuffers.Long
             */
            low() {
                return this.bb.readUint64(this.bb_pos);
            }
            ;
            /**
             * @returns flatbuffers.Long
             */
            high() {
                return this.bb.readUint64(this.bb_pos + 8);
            }
            ;
            /**
             * @param flatbuffers.Builder builder
             * @param flatbuffers.Long low
             * @param flatbuffers.Long high
             * @returns flatbuffers.Offset
             */
            static createUUID(builder, low, high) {
                builder.prep(8, 16);
                builder.writeInt64(high);
                builder.writeInt64(low);
                return builder.offset();
            }
            ;
        }
        proto.UUID = UUID;
    })(proto = Mod.proto || (Mod.proto = {}));
})(Mod = exports.Mod || (exports.Mod = {}));
